###
### Language
###
language: c


###
### Choose OS
###
os:
  - linux
  - osx


###
### Install requirements
###
install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      until sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ trusty-backports restricted main universe"; do sleep 5; done;
      until sudo apt-get update -qq; do sleep 5; done;
      until sudo apt-get install -qq -y shellcheck; do sleep 5; done;
    else
      until brew update; do sleep 5; done;
      until brew install --with-default-names make; do sleep 5; done;
      until brew install shellcheck; do sleep 5; done;
    fi
  - make --version
  - bash --version
  - shellcheck --version


###
### Test
###
before_script:
  - make lint

script:
  - make test
